replicaCount: 1

image:
  repository: solomon/nginx
  tag: vi
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: ""
  className: ""
  annotations: {}
  hosts:
    - host: chart-syself.local
      paths:
        - /
  tls: []
