apiVersion: v1
kind: Service
metadata:
  name: {{ include "syself-helm-chart.fullname" . }}
  labels:
    {{- include "syself-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "syself-helm-chart.name" . }}
