replicaCount: 1

image:
  repository: solomon/nginx
  tag: vi
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: ""
  className: ""
  annotations: {}
  hosts:
    - host: chart-syself.local
      paths:
        - /
  tls: []
  
persistence:
  enabled: true
  existingClaim: nginx-volume-claim
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  storageClass: gp2
